### ISSUE TITLE
Integrate Detekt linter

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#250]
I was checking the [intellij-platform-plugin-template](https://github.com/JetBrains/intellij-platform-plugin-template), and saw a `detekt` linter in addition to `ktlint`. Do you think we can also integrate it with WMP @Unthrottled? This would be a part where we add missing goodies here in WMP based on the template repo.

https://github.com/JetBrains/intellij-platform-plugin-template/blob/e44bf3c3ec0d1fd1ac9e1f78bc5bda7eacb14257/build.gradle.kts#L15-L18
```
    // detekt linter - read more: https://detekt.github.io/detekt/gradle.html
    id("io.gitlab.arturbosch.detekt") version "1.14.2"
    // ktlint linter - read more: https://github.com/JLLeitschuh/ktlint-gradle
    id("org.jlleitschuh.gradle.ktlint") version "9.4.1"
```

[Reference](https://detekt.github.io/detekt/gradle.html)

**Comment by Unthrottled** [comment]
Yes! That would be nice!

Suggested extension to the detekt config

```yml
exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: true
    values: []

empty-blocks:
  active: false
```

Would also like detekt to be configured to autocorrect as well.
